[x64_package_linux_rust_pkg_gen]
toolchains = [
    {edition="2021", channel="1.83.0", profile="complete", components=["rustfmt", "rustc", "cargo"]}
]

[x64_package_linux_rust_pkg_gen.meta]
offline = true
platforms = [
    "x86_64-unknown-linux-gnu"
]
targets = [
    "x86_64-unknown-linux-gnu"
]

[x64_package_linux_rust_pkg_gen.crates]
"*-nightly" = {"rust-embed"="2.0.90"}