[x64_package_linux_rust_pkg_gen]
toolchains = [
    { edition = "2021", channel = "nightly", profile = "complete", components = [
        "rustfmt",
        "rustc",
        "cargo",
    ], crate_id = "2021-nightly-complete", platforms = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"], targets = ["x86_64-unknown-linux-gnu"]},
]

[x64_package_linux_rust_pkg_gen.meta]
offline = true

[x64_package_linux_rust_pkg_gen.crates]
"2021-nightly-complete" = { "syn" = "2.0.90" }
